- name:
  hosts: managed-nodes
  remote_user: ec2-user
  vars_prompt:
  - name: secret_key
    prompt: What is the value of SECRET_KEY?
    private: true
  - name: trello_api_key
    prompt: What is your TRELLO_API_KEY?
    private: true
  - name: trello_api_token
    prompt: What is your TRELLO_API_TOKEN?
    private: true

  tasks:
  - name: Install git and python3
    ansible.builtin.yum:
      name:
        - git
        - python3
      state: present
    become: yes
  - name: Install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: /home/ec2-user/.local/bin/poetry
  - name: Create directory for todoapp
    ansible.builtin.file:
      path: /opt/todoapp
      owner: ec2-user
      state: directory
    become: yes
  - name: Get code from git
    ansible.builtin.git:
      repo: https://github.com/PhoebeJackson1/DevOps-Course-Starter.git
      dest: /opt/todoapp
      version: exercise-4
  - name: Install project dependencies
    ansible.builtin.command: /home/ec2-user/.local/bin/poetry install
    args:
      chdir: /opt/todoapp/
  - name: Create .env file
    ansible.builtin.template:
      src: ../.env.j2
      dest: /opt/todoapp/.env
  - name: Copy todoapp.service to correct place
    ansible.builtin.copy:
      src: todoapp.service
      dest: /etc/systemd/system/todoapp.service
    become: yes
  - name: Start app
    ansible.builtin.systemd:
      name: todoapp
      daemon_reload: true
      state: restarted
    become: yes


