name: Continuous Integration
on: 
  push:
    paths-ignore:
        '**.md'
  pull_request:
    paths-ignore:
        '**.md'

  

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker build --target test --tag todo-app:test .
    - name: Run tests
      run: docker run --env-file .env.test todo-app:test
  job-two: 
    name: Job two
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/head/exercise-9' && github.event_name == 'push'
    steps:
      - run: echo Publishing!