name: Continuous Integration
on: 
  push:
    paths-ignore:
        '**.md'
  pull_request:
    paths-ignore:
        '**.md'

  

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker build --target test --tag todo-app:test .
    - name: Run tests
      run: docker run --env-file .env.test todo-app:test
  build-and-push: 
    name: Build and push
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/exercise-9'
    steps:
      - run: echo Publishing!
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: phoebejackson
          password: ${{ secrets.DOCKERHUB_PAT }}
      - uses: actions/checkout@v4
      - name: Build
        run: docker build --target production --tag phoebejackson/todo-app:prod .
      - name: Push
        run: docker push phoebejackson/todo-app:prod